/*
 *  ======== ti_ble_config.h ========
 *  Configured BLE module definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */

#ifndef TI_BLE_CONFIG_H
#define TI_BLE_CONFIG_H

#include "ti/ble/stack_util/bcomdef.h"
#include "ti/ble/host/gap/gapgattserver.h"
#include "ti/ble/host/gap/gap_advertiser.h"
#include "ti/ble/host/gapbondmgr/gapbondmgr.h"


// The GAP profile role
extern uint8_t profileRole;
// GAP GATT Service (GGS) parameters
extern uint8_t attDeviceName[GAP_DEVICE_NAME_LEN];
extern void init_profiles(void);

//Random Address
extern uint8_t pRandomAddress[B_ADDR_LEN];

// Address mode of the local device
// Note: When using the DEFAULT_ADDRESS_MODE as ADDRMODE_RANDOM or
// ADDRMODE_RP_WITH_RANDOM_ID, GAP_DeviceInit() should be called with
// it's last parameter set to a static random address
#define DEFAULT_ADDRESS_MODE                  ADDRMODE_RP_WITH_PUBLIC_ID

// How often to read current RPA (in ms)
#define READ_RPA_PERIOD                       3000

#define BLE_CONFIG_NUM_ADV_SETS    1
extern void BleConfig_initAdvSets(uint8_t* advHandles, uint8_t* advHandlesStatus);
extern void BleConfig_startAdvSets(uint8_t* advHandles, uint8_t* advHandlesStatus, uint8_t size);
extern void BleConfig_stopAdvSets(uint8_t* advHandles, uint8_t* advHandlesStatus, uint8_t size);

/*********************************************************************
 * Bond Manager Configuration
 */

extern gapBondParams_t gapBondParams;

extern uint8_t pairMode;
extern uint8_t mitm;
extern uint8_t ioCap;
extern uint8_t bonding;
extern uint8_t secureConnection;
extern uint8_t authenPairingOnly;
extern uint8_t autoSyncAL;
extern uint8_t eccReGenPolicy;
extern uint8_t KeySize;
extern uint8_t removeLRUBond;
extern uint8_t KeyDistList;
extern uint8_t eccDebugKeys;
extern uint8_t allowDebugKeys;
extern uint8_t eraseBondWhileInConn;
extern uint8_t sameIrkAction;

extern void setBondManagerParameters();



//Primary PHY Parameters

// Default PHY for scanning
#define DEFAULT_SCAN_PHY                        SCAN_PRIM_PHY_1M

//Default Scan type (Active/Passive)
#define DEFAULT_SCAN_TYPE                       SCAN_TYPE_ACTIVE

// Scan period
#define DEFAULT_SCAN_PERIOD                     0

// Default scan interval (in 625 us ticks)
#define DEFAULT_SCAN_INTERVAL                   800

// Default scan window   (in 625 us ticks)
#define DEFAULT_SCAN_WINDOW                     800

// Default scan duration in 10 ms
#define DEFAULT_SCAN_DURATION                   100

// Advertising report fields to keep in the list
#define ADV_RPT_FIELDS                          (SCAN_ADVRPT_FLD_ADDRESS | SCAN_ADVRPT_FLD_ADDRTYPE)

// Scanner Filter Policy
#define SCANNER_FILTER_POLICY                   SCAN_FLT_POLICY_ALL

// Scanner Filter PDU Type
#define SCANNER_FILTER_PDU_TYPE                  (SCAN_FLT_PDU_COMPLETE_ONLY | SCAN_FLT_PDU_CONNECTABLE_ONLY)

// Scanner Filter Minimum RSSI
#define SCANNER_FILTER_MIN_RSSI                  -128

// Scanner Discoverable Mode Filter
#define SCANNER_FILTER_DISC_MODE                 SCAN_FLT_DISC_DISABLE

// Scanner Duplicate Filter
#define SCANNER_DUPLICATE_FILTER                 SCAN_FLT_DUP_ENABLE

// TRUE to filter discovery results on desired service UUID
#define DEFAULT_DEV_DISC_BY_SVC_UUID            true

// Maximum number of advertising reports
#define APP_MAX_NUM_OF_ADV_REPORTS              20



// Pass parameter updates to the app for it to decide.
#define DEFAULT_PARAM_UPDATE_REQ_DECISION       GAP_UPDATE_REQ_PASS_TO_APP

// Pass parameter updates to the app for it to decide.
#define DEFAULT_SEND_PARAM_UPDATE_REQ

// Delay (in ms) after connection establishment before sending a parameter update requst
#define SEND_PARAM_UPDATE_DELAY                 6000

// Minimum connection interval (units of 1.25ms) if automatic parameter update
// request is enabled
#define DEFAULT_DESIRED_MIN_CONN_INTERVAL      40

// Maximum connection interval (units of 1.25ms) if automatic parameter update
// request is enabled
#define DEFAULT_DESIRED_MAX_CONN_INTERVAL      40

// Peripheral latency to use if automatic parameter update request is enabled
#define DEFAULT_DESIRED_PERIPHERAL_LATENCY     0

// Supervision timeout value (units of 10ms) if automatic parameter update
// request is enabled
#define DEFAULT_DESIRED_CONN_TIMEOUT           600

typedef struct {
    uint8_t *advData;
    uint8_t advDataLen;
    uint8_t *scanRspData;
    uint8_t scanRspDataLen;
    GapAdv_params_t *advParams;
} AdvSetInfo_t;


// Advertisement Set Number 1
extern GapAdv_params_t advParams1;
extern uint8_t advData1[17];
extern uint8_t scanResData1[17];


// PADV Time Sync parameters

#endif /* TI_BLE_CONFIG_H */
