################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
common/lib_opt/ctrl_opt_adaptivity.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_adaptivity.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_adv_conn.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_adv_conn.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_adv_nconn.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_adv_nconn.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ae.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ae.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ble_health.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ble_health.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_cm.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_cm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_coex.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_coex.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_connectable.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_connectable.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_connection_handover.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_connection_handover.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_cs.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_cs.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_cs_test.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_cs_test.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_dmm.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_dmm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_dmm_dynamic_priority.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_dmm_dynamic_priority.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ext_vendor_specific_cmd.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ext_vendor_specific_cmd.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_health_check.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_health_check.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_initiator.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_initiator.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_legacy_cmd.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_legacy_cmd.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_padv.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_padv.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_past_receiver.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_past_receiver.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_past_sender.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_past_sender.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_pawr_advertiser.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_pawr_advertiser.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_pawr_scan.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_pawr_scan.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_power_control.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_power_control.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_pscan.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_pscan.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_rssi_monitor.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_rssi_monitor.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_scanner.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_scanner.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_ts_periodic.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_ts_periodic.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/ctrl_opt_vendor_specific_cmd.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/ctrl_opt_vendor_specific_cmd.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/host_opt_gap_bond_mgr.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/host_opt_gap_bond_mgr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/host_opt_gap_past_receiver.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/host_opt_gap_past_receiver.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/host_opt_gap_past_sender.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/host_opt_gap_past_sender.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/host_opt_gap_pawr_adv.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/host_opt_gap_pawr_adv.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

common/lib_opt/host_opt_gap_pawr_scan.o: E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/lib_opt/src/host_opt_gap_pawr_scan.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"E:/CCS12.8.1/ccs/tools/compiler/ti-cgt-armllvm_3.2.2.LTS/bin/tiarmclang.exe" -c @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/build_components.opt" @"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/ble/stack_util/config/factory_config.opt"  -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv5-sp-d16 -mlittle-endian -mthumb -Oz -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mbedtls/ti" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/bootutil/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/mcuboot/boot/ti/source/mcuboot_app" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/common/cc26xx/flash_interface" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/drivers/rcl" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/ti/posix/ticlang" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/kernel/freertos" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/include" -I"E:/ti/simplelink_lowpower_f3_sdk_9_20_00_81/source/third_party/freertos/portable/GCC/ARM_CM33_NTZ/non_secure" -DICALL_NO_APP_EVENTS -DMBEDTLS_CONFIG_FILE="configs/config-hsm.h" -DMBEDTLS_PSA_CRYPTO_CONFIG_FILE="configs/config-psa-crypto-hsm.h" -DNVOCMP_NVPAGES=6 -DNVOCMP_POSIX_MUTEX -DNVOCMP_NWSAMEITEM=1 -DFREERTOS -DUSE_HSM -g -Wunused-function -Wall -ffunction-sections -MMD -MP -MF"common/lib_opt/$(basename $(<F)).d_raw" -MT"$(@)" -I"E:/CCS12.8.1/workspace_v12/basic_ble_LP_EM_CC2745R10_Q1_freertos_ticlang/Debug/syscfg" -std=c99 $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


