/*
 *  ======== ti_secure_boot_properties.h ========
 *  Secure Boot definitions for CC27XX devices.
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 *
 */

#ifndef __SECURE_BOOT_PROPERTIES_H__
#define __SECURE_BOOT_PROPERTIES_H__

/* Secure Boot is DISABLED - No definitions generated */

#endif
